name: Build docker

on:
  push:
  pull_request:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ros2-jazzy-harmonic-image .

      - name: Run Build in Docker Container
        run: |
          docker run --rm -v ${{ github.workspace }}:/ros_ws ros2-jazzy-harmonic-image /bin/bash -c "
          cd /ros_ws
          source /opt/ros/jazzy/setup.bash &&
          rosdep update &&
          rosdep install --from-paths src --ignore-src -r -y &&
          colcon build --symlink-install --event-handlers console_direct+"
