name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: humble
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up ROS 2 ${{ env.ROS_DISTRO }} Environment
        uses: ros-tooling/setup-ros@v0.3
        with:
          ros-distro: ${{ env.ROS_DISTRO }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build Packages
        run: |
          colcon build --symlink-install --event-handlers console_direct+

      - name: Source Environment
        shell: bash -l {0}
        run: source install/setup.bash

      - name: Run Tests
        run: |
          colcon test
          colcon test-result --verbose
