name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: jazzy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up ROS 2 ${{ env.ROS_DISTRO }} Environment
        uses: ros-tooling/setup-ros@v0.3
        with:
          ros-distro: ${{ env.ROS_DISTRO }}

      - name: Install Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install flake8 flake8-docstrings

      - name: Lint Python Code
        run: |
          # Check for critical errors
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # Check for style and complexity with non-zero exit on failure
          flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install C++ Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Lint C++ Code
        run: |
          find src/ -name '*.cpp' -o -name '*.hpp' | xargs clang-format -style=file -output-replacements-xml | grep -c "<replacement " && echo "Code style issues found." && exit 1 || echo "No code style issues found."

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ros2-jazzy-harmonic-image .

      - name: Run Build in Docker Container
        run: |
          docker run --rm -v /home/runner/work/Self-Balancing-Robot-ROS2-Gazebo/Self-Balancing-Robot-ROS2-Gazebo:/ros_ws -w /ros_ws --user $(id -u):$(id -g) -e ROS_HOME=/ros_ws/.ros ros2-jazzy-harmonic-image /bin/bash -c "
          cd /ros_ws &&
          source /opt/ros/jazzy/setup.bash &&
          mkdir -p /ros_ws/.ros &&
          rosdep update &&
          rosdep install --from-paths src --ignore-src -r -y &&
          colcon build --symlink-install --event-handlers console_direct+"
