name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: humble
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up ROS 2 ${{ env.ROS_DISTRO }} Environment
        uses: ros-tooling/setup-ros@v0.3
        with:
          ros-distro: ${{ env.ROS_DISTRO }}

      - name: Install Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install flake8 flake8-docstrings

      - name: Lint Python Code
        run: |
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Install C++ Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format

      - name: Lint C++ Code
        run: |
          find src/ -name '*.cpp' -o -name '*.hpp' | xargs clang-format -style=file -output-replacements-xml | grep -c "<replacement " && echo "Code style issues found." && exit 1 || echo "No code style issues found."
          